name: PHPUnit tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [5.6, 7.0, 7.1, 7.2, 7.3]
    steps:
      - uses: docker://docker.io/byjg/php:${{ matrix.php_version }}
      - run: |
          composer install
          vendor/bin/phpunit